### ISSUE TITLE
I can't show the DoltLab homepage

### ISSUE THREAD

**Issue by takashi-nakakido** [dolthub/doltlab-issues#70]
I followed the installation guide,
The following error message appears and I cannot view the DoltLab home page.

https://docs.dolthub.com/products/doltlab/installation

`
Error: metrics enabled but GA_TRACKING_ID not specified in server config
    at _app-01bcbb53c703ecb9.js:14:302241
    at Object.useMemo (framework-8ea3c61dd4c96877.js:25:67226)
    at t.useMemo (framework-8ea3c61dd4c96877.js:41:5986)
    at Q (_app-01bcbb53c703ecb9.js:14:302000)
    at lb (framework-8ea3c61dd4c96877.js:25:60916)
    at i (framework-8ea3c61dd4c96877.js:25:119474)
    at uI (framework-8ea3c61dd4c96877.js:25:99113)
    at framework-8ea3c61dd4c96877.js:25:98980
    at uM (framework-8ea3c61dd4c96877.js:25:98987)
    at ux (framework-8ea3c61dd4c96877.js:25:95739)
`

**Comment by coffeegoddd** [comment]
@takashi-nakakido is this for the latest DoltLab version `v1.0.3`?

Can you share the environment variables you used to start DoltLab with the `./start-doltlab.sh` script?

**Comment by takashi-nakakido** [comment]
>@takashi-nakakido is this for the latest DoltLab version v1.0.3?
→Yes.

./start-doltlab.sh script
→I have created a script with the following settings.
export HOST_IP=<IPv4 public IP>
export DOLT_PASSWORD=<Password>
export DOLTHUBAPI_PASSWORD=<Password>
export EMAIL_HOST=localhost
export EMAIL_PORT=<dummy port>
export NO_REPLY_EMAIL=XXXXXXXX@gmail.com
export EMAIL_USERNAME=XXXX
export EMAIL_PASSWORD=<Password>

I have a server up and running on AWS Cloud9. I wanted to try dolt easily so I don't have an SMTP server ready.
Is an SMTP server required?

**Comment by takashi-nakakido** [comment]
@coffeegoddd 

>@takashi-nakakido is this for the latest DoltLab version v1.0.3?
→Yes.

./start-doltlab.sh script
→I have created a script with the following settings.
export HOST_IP=<IPv4 public IP>
export DOLT_PASSWORD=<Password>
export DOLTHUBAPI_PASSWORD=<Password>
export EMAIL_HOST=localhost
export EMAIL_PORT=<dummy port>
export NO_REPLY_EMAIL=XXXXXXXX@gmail.com
export EMAIL_USERNAME=XXXX
export EMAIL_PASSWORD=<Password>

I have a server up and running on AWS Cloud9. I wanted to try dolt easily so I don't have an SMTP server ready.
Is an SMTP server required?

**Comment by coffeegoddd** [comment]
@takashi-nakakido thanks for your responses. So the error `Error: metrics enabled but GA_TRACKING_ID not specified in server config` occurs because the DoltLab application is not getting the value of `HOST_IP` when it starts up, so it starts the DoltLab application in _DoltHub_ mode, which produces this error.

DoltLab has not been tested on AWS Cloud9, so it's possible running DoltLab in this environment is interfering with DoltLab's `./start-doltlab.sh` script and assumptions. 

While DoltLab is running can you run `docker inspect doltlab_doltlabui_1` and share the environment variables in the output? It will look something like this:
```
            "Env": [
                "NODE_OPTIONS=--max-old-space-size=16384",
                "DOLTHUB_VERSION=doltlab-v1.0.3",
                "STRIPE_API_KEY=does_not_work",
                "HOST_IP=doltlab.dolthub.com",
                "INTERNAL_GRAPHQLAPI_URL=http://doltlabenvoy:10080/graphql",
                "EVENTSAPI_URL=https://eventsapi.dolthub.com",
                "DOLTHUB_METRICS_ENABLED=true",
                "ENTERPRISE_EDITION=",
                "ALT_LOGO=",
                "ALLOW_COLOR_OVERRIDES=",
                "COLOR_OVERRIDE_RGB_ACCENT_1=",
                "COLOR_OVERRIDE_RGB_BACKGROUND_ACCENT_1=",
                "COLOR_OVERRIDE_RGB_BACKGROUND_GRADIENT_START=",
                "COLOR_OVERRIDE_RGB_BUTTON_1=",
                "COLOR_OVERRIDE_RGB_BUTTON_2=",
                "COLOR_OVERRIDE_RGB_LINK_1=",
                "COLOR_OVERRIDE_RGB_LINK_2=",
                "COLOR_OVERRIDE_RGB_LINK_LIGHT=",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=16.14.0",
                "YARN_VERSION=1.22.17",
                "NODE_ENV=production"
            ],
```

Based on the error, I would expect to see `HOST_IP=""` or not at all in your output.

Regarding "Is an SMTP server required?", it is required for the full functionality of DoltLab. Without a configured, working SMTP server, I believe only the `admin` user can use the DoltLab instance in a meaningful way.

**Comment by takashi-nakakido** [comment]
@coffeegoddd 

The following was displayed.

```
            "Env": [
                "NODE_OPTIONS=--max-old-space-size=16384",
                "DOLTHUB_VERSION=doltlab-v1.0.3",
                "STRIPE_API_KEY=does_not_work",
                "HOST_IP=",
                "INTERNAL_GRAPHQLAPI_URL=http://doltlabenvoy:10080/graphql",
                "EVENTSAPI_URL=https://eventsapi.dolthub.com",
                "DOLTHUB_METRICS_ENABLED=true",
                "ENTERPRISE_EDITION=",
                "ALT_LOGO=",
                "ALLOW_COLOR_OVERRIDES=",
                "COLOR_OVERRIDE_RGB_ACCENT_1=",
                "COLOR_OVERRIDE_RGB_BACKGROUND_ACCENT_1=",
                "COLOR_OVERRIDE_RGB_BACKGROUND_GRADIENT_START=",
                "COLOR_OVERRIDE_RGB_BUTTON_1=",
                "COLOR_OVERRIDE_RGB_BUTTON_2=",
                "COLOR_OVERRIDE_RGB_LINK_1=",
                "COLOR_OVERRIDE_RGB_LINK_2=",
                "COLOR_OVERRIDE_RGB_LINK_LIGHT=",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=16.14.0",
                "YARN_VERSION=1.22.17",
                "NODE_ENV=production"
            ],
```

In which environment should I run it?
The same error was displayed when I ran it in the gcp environment.

**Comment by coffeegoddd** [comment]
So in your output above HOST_IP is empty (or set to an empty string) which is why youre getting the error. 

The ./start-doltlab.sh returns an error if you try to run it and HOST_IP is unset or an empty string, so now sure why its not doing so for you. 

HOST_IP should be set to the IP address of the host running DoltLab.

We suggest running DoltLab on an Ubuntu AWS EC2 instance. Checkout this starter blog https://www.dolthub.com/blog/2022-02-22-getting-started-doltlab-video/

**Comment by takashi-nakakido** [comment]
@coffeegoddd 
Thank you very much.
When I ran it on EC2, it worked fine!
![Uploading スクリーンショット 2023-08-20 19.29.28.png…]()

**Comment by takashi-nakakido** [comment]
<img width="761" alt="スクリーンショット 2023-08-20 19 29 28" src="https://github.com/dolthub/doltlab-issues/assets/112357115/fe1b8fda-0676-4daa-96c0-67d9f2bb9101">

**Comment by bpf120** [comment]
Hi @takashi-nakakido, Thank you for checking out DoltLab. We'd love to learn about your Dolt and DoltLab use case too. You can [email me](mailto:brianf@dolthub.com) or come by our [Discord](https://discord.gg/gqr7K4VNKe).
